language: java
sudo: true

jdk:
  - oraclejdk8

before_script:
  - mvn install -q -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true

script:
  mvn install -q -Dmaven.test.redirectTestOutputToFile=true

after_success:
  - chmod -R 777 ./travis/deploy-to-sonatype.sh
  - ./travis/deploy-to-sonatype.sh
