language: java

jdk:
  - oraclejdk8

script: mvn --settings .travis/settings.xml clean

deploy:
  -
    provider: script
    script: .travis/deploy-to-sonatype.sh
    skip_cleanup: true
    on:
      repo: storezhang/utils
      tags: true
      jdk: oraclejdk8


notifications:
  email:
    - admin@ruijc.com
