language: java

jdk:
  - oraclejdk8

script: mvn cobertura:cobertura --settings .travis/settings.xml clean verify

after_success:
  - chmod -R 777 .travis/deploy-to-sonatype.sh
  - .travis/deploy-to-sonatype.sh
  - bash <(curl -s https://codecov.io/bash)