language: java
sudo: false

jdk:
  - oraclejdk8

before_script:
  - mvn install -q -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true

script:
  mvn install -q -Dmaven.test.redirectTestOutputToFile=true

after_success:
  - chmod -R 777 ./travis/deploy-to-sonatype.sh
  - ./travis/deploy-to-sonatype.sh
env:
  global:
    - secure: "m/g3obX+91swDLggqVcoSYidVcy2LaleBjQnL+FXrq1ur5U5Fh97ApcADfKjMfBsOE0InsHnDdCoousch/iKK03od+YDV9GJiTj08NB7MTGwWqlfVwLpqxWkWgBUSiQwue5QpAEox0jpRwJWSWdbxkk28VbDXEtDqQnLPTFKRcGp0629vkZxMvKWaeTsE1p3LXHXi6icEW7LaMfXHzai3gh5XKAWwKq/k80W/AFbh3a2Eg5ytMJ0l4PVZxV7HF0UxnslEyytbZ8ZuZjkyfuD9fsY5YNW140DteW4M6B4jMpLnRK3eeZ/lx7ut4maznOkrX4eV8MFJu14Q0L4KxNuUgDh7a7i1Mzh35LlMuwuh0Z3cxi23QyeTQY51/LgQ4C/jf4RVMLVB1VPN7HsfzaIWC9K9OOsXzZwddB6qaDic9BGTkVA55vste8D17Y8xPuJyRMuy9zXE9MYl59IbbpTKpRTNg8m89ZGTtYdrw5aHfFlt3ianoQdDCZfNQpbLUWLLWbJohyZQZf/KO16LYRpArPvtGAOUsBF19SAb/dxCdvsMoYPyEbWnOiFO5LeOyaEVzSdYQFMfySXKWl71dL+J8ZIPCr6CR07lH+iJyUduRV67nYRUwgXl9W7P64WuF9G/LZX8tW59FFeIy30mN1aeoM6icmijG4Z9R+H2Ibdpo0="
    - secure: "cVeqMi6OP3MTwckqJIhP4BEqdq4QFe/HeeorK5ZraW22SRSYbEczt8ljyVOFWR9TvM0ST1w5x4H4pEMLaY5edW0jiGZB1i5lrzwHj/QCiKJNCzg7grsXx0R4kSQKTnvJ3e+ndWV4pEX0opflQWkTj76UTPqv7kLdvu3/14btbjdUkkcGyU29yYwqlYcjbhTDhf8O1bvOHX1lbgy0cTK8eqOnNWGGGSptWW+bsjW0iKy7C4fPIRtLtaPqOp8zUgxtYvTi/2Z7/WcqF+/Kg9EPi+5xAF73v4USerXDHBTsNTDo5hbvyoB6NvVRHe7nGuX0zNyUie1mkSq4PhtvSWSVsdihiVT9fYr2KXicIDoDn1MSf0wUjg+OewHMBxZxaUHJg9MBk9L1aVbTnJqnZKlL/blrneKsAYu17A2q0TMXQHD83+ukwdxWHmEK52OxJoldle51vsiV7+OVbDDaQjj9r9di9IO8oIf3XC26VPB7A9hzi72XjT9E/ga0WrGsJno48AcyJiJRGYEsiDOOW4dURzABtRLd6tLA60pmWf88gsanYueHhAykzU/eKMFgb5AHDFTOGQ05PBIcdkY20E8eRO3O4zw6coGq18TQwyyxFInlxpyq2q3+DQKFwe6fNyraeKGmsqK5BYHo2zyQw/fMV0pbz+4loynn/Da+/E6Wtcs="
